### ISSUE TITLE
bodhi-client fails to be installed

### ISSUE THREAD

**Issue by junaruga** [xsuchy/fedora-packages-ng#5]
Related to this error on Travis CI.
https://travis-ci.org/xsuchy/fedora-packages-ng/jobs/602858695

`pip install bodhi-client` fails to be installed.
https://pypi.org/project/bodhi-client/

In case of docker-compose case, `python3-bodhi-client` is used.
https://apps.fedoraproject.org/packages/python3-bodhi-client

```
$ python3 -m venv ./venv

$ source venv/bin/activate

(venv) $ pip install bodhi-client
Collecting bodhi-client
  Downloading https://files.pythonhosted.org/packages/0b/0e/a18b82be6e92a1c0586bef8e311a51f92b55ea870286c2dd37fe1d8e1173/bodhi-client-4.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/bodhi.egg-info
    writing pip-egg-info/bodhi.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/bodhi.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/bodhi.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/bodhi.egg-info/SOURCES.txt'
    package init file 'bodhi/__init__.py' not found (or not a regular file)
    reading manifest file 'pip-egg-info/bodhi.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/bodhi.egg-info/SOURCES.txt'
    running egg_info
    creating pip-egg-info/bodhi_client.egg-info
    writing pip-egg-info/bodhi_client.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/bodhi_client.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/bodhi_client.egg-info/entry_points.txt
    writing requirements to pip-egg-info/bodhi_client.egg-info/requires.txt
    writing top-level names to pip-egg-info/bodhi_client.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/bodhi_client.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/bodhi_client.egg-info/SOURCES.txt'
    reading manifest template 'CLIENT_MANIFEST.in'
    writing manifest file 'pip-egg-info/bodhi_client.egg-info/SOURCES.txt'
    running egg_info
    creating pip-egg-info/bodhi_messages.egg-info
    writing pip-egg-info/bodhi_messages.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/bodhi_messages.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/bodhi_messages.egg-info/entry_points.txt
    writing requirements to pip-egg-info/bodhi_messages.egg-info/requires.txt
    writing top-level names to pip-egg-info/bodhi_messages.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/bodhi_messages.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/bodhi_messages.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/bodhi_messages.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-i9ip6j_n/bodhi-client/setup.py", line 199, in <module>
        server_packages.remove('bodhi')
    ValueError: list.remove(x): x not in list
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-i9ip6j_n/bodhi-client/
You are using pip version 9.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by junaruga** [comment]
It seems that we faced this issue.
https://github.com/fedora-infra/bodhi/issues/2401

**Comment by junaruga** [comment]
@xsuchy I just merged my pull-request.
The change is to run "Setup without docker - pipenv" case on Fedora from Ubuntu.

But there is still error on the case.

https://travis-ci.org/xsuchy/fedora-packages-ng/jobs/603830526#L1064

```
+ pipenv run python3 manage.py flake
...
ModuleNotFoundError: No module named 'bodhi'
```

The reason is as `bodhi-client` in `Pipfile` makes error, we can not set in it.
But Pipenv only see pip packages in `Pipfile` as default like this.

```
[tester@523a16408ad0 work]$ python3 -c 'import bodhi;'
[tester@523a16408ad0 work]$ pipenv run python3 -c 'import bodhi;'
Loading .env environment variables…
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'bodhi'
```

pipenv command has `--site-packages`. But it is still error with the option.

```
$ pipenv --site-packages run python3 -c 'import bodhi'
Loading .env environment variables…
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'bodhi'
```

As you do not see the error on your local environment, I think you have an idea to fix the error.
